
version: '3'

services:
  web:
    build:
      context: .
      dockerfile : dockerfile
    image: web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --prot 8000"
    env_file:
      - ".env"
    environment:
      - DEBUG=1

  db:
    image: mysql:8
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.7-alpine
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PW}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "15672"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    image: web
    build:
      context: .
      dockerfile : dockerfile
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: sh -c "celery -A ${CELERY_NAME} worker --pool=${CELERY_POOL} --concurrency=${CELERY_CONCURRENCY} -E --loglevel=info"
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower:2.0
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    expose:
      - 5555
    depends_on:
      - redis
      - db

volumes:
  mysql-db-data:
